services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp_tests
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot --silent"]
      interval: 2s
      timeout: 2s
      retries: 60
      start_period: 5s
