#!/usr/bin/env bash
set -euo pipefail

echo "[init] Starting SmartAlloc container init..."

WP_VERSION="${WP_VERSION:-6.6.2}"
DB_HOST="${WP_TESTS_DB_HOST:-db}"
DB_NAME="${WP_TESTS_DB_NAME:-wordpress_tests}"
DB_USER="${WP_TESTS_DB_USER:-root}"
DB_PASS="${WP_TESTS_DB_PASS:-root}"

echo "[init] WP_VERSION=${WP_VERSION}"
echo "[init] DB=${DB_USER}@${DB_HOST}/${DB_NAME}"

echo "[init] Waiting for database to be ready..."
for i in {1..60}; do
  if mysqladmin --skip-ssl ping -h"${DB_HOST}" -u"${DB_USER}" -p"${DB_PASS}" --silent >/dev/null 2>&1; then
    echo "[init] Database is up."
    break
  fi
  sleep 1
done

if ! mysqladmin --skip-ssl ping -h"${DB_HOST}" -u"${DB_USER}" -p"${DB_PASS}" --silent >/dev/null 2>&1; then
  echo "[init] ERROR: Database did not become ready in time." >&2
  exit 1
fi

echo "[init] Installing Composer dependencies..."
composer install --no-interaction --prefer-dist

echo "[init] Setting up WordPress PHPUnit (WP_VERSION=${WP_VERSION})..."
composer setup:wp-tests || true

# Create wp-tests-config.php if missing (points to ./wordpress)
PROJECT_DIR="$(pwd)"
CONFIG_FILE="$PROJECT_DIR/wp-tests-config.php"
if [ ! -f "$CONFIG_FILE" ]; then
  echo "[init] Creating wp-tests-config.php at $CONFIG_FILE"
  cat > "$CONFIG_FILE" <<'PHP'
<?php
/* WordPress tests configuration (generated by docker/init.sh) */

define( 'DB_NAME', getenv('WP_TESTS_DB_NAME') ?: 'wordpress_tests' );
define( 'DB_USER', getenv('WP_TESTS_DB_USER') ?: 'root' );
define( 'DB_PASSWORD', getenv('WP_TESTS_DB_PASS') ?: 'root' );
define( 'DB_HOST', getenv('WP_TESTS_DB_HOST') ?: 'db' );
define( 'DB_CHARSET', 'utf8' );
define( 'DB_COLLATE', '' );

$table_prefix = 'wptests_';

define( 'WP_DEBUG', true );
define( 'WP_TESTS_DOMAIN', 'example.org' );
define( 'WP_TESTS_EMAIL', 'admin@example.org' );
define( 'WP_TESTS_TITLE', 'Test Blog' );

// Point to the WordPress core downloaded to ./wordpress
define( 'ABSPATH', dirname(__FILE__) . '/wordpress/' );
PHP
fi

echo "[init] Validating test environment..."
composer validate:test-env || true

echo "[init] Done. You can now run tests: vendor/bin/phpunit -v"
