#!/usr/bin/env bash
set -euo pipefail

PHP_VERSION="${1:-8.2}"
WP_VERSION="${2:-latest}"

echo "# 📊 داشبورد پروژه SmartAlloc" > PROJECT_STATE.md
echo "**آخرین بروزرسانی**: $(date -u '+%Y-%m-%d %H:%M UTC')" >> PROJECT_STATE.md
echo "**شاخه**: $(git branch --show-current 2>/dev/null || echo unknown)" >> PROJECT_STATE.md
echo "**کامیت**: $(git log -1 --pretty='%h %s' 2>/dev/null || echo none)" >> PROJECT_STATE.md
echo "**PHP**: $PHP_VERSION | **وردپرس**: $WP_VERSION" >> PROJECT_STATE.md

echo -e "\n## 🎯 وضعیت کلی" >> PROJECT_STATE.md
if [ -f coverage.xml ]; then
  COV=$(grep -o 'lines percent="[0-9.]*"' coverage.xml | head -1 | sed 's/[^0-9.]*//g')
  echo "- **پوشش تست**: ${COV}%" >> PROJECT_STATE.md
else
  echo "- **پوشش تست**: ناموجود" >> PROJECT_STATE.md
fi

echo -e "\n## 🔒 وضعیت امنیتی" >> PROJECT_STATE.md
if ls psalm*.xml >/dev/null 2>&1; then
  ERR=$(grep -ci "error" psalm*.xml || true)
  echo "- خطاهای Psalm: ${ERR}" >> PROJECT_STATE.md
else
  echo "- گزارش Psalm ناموجود" >> PROJECT_STATE.md
fi

echo -e "\n## 📋 وضعیت پیاده‌سازی" >> PROJECT_STATE.md
echo "| ویژگی | وضعیت | تست | امنیت |" >> PROJECT_STATE.md
echo "|---|---|---|---|" >> PROJECT_STATE.md
for F in "Allocator|src/Services/AllocationService.php|tests/Unit/AllocatorTest.php" \
         "RBAC|src/Http/RestController.php|tests/VIP/SecurityAuditTest.php" \
         "Export|src/Services/ExportService.php|tests/Integration/ExportTest.php" \
         "Events|src/Event/EventBus.php|tests/Unit/EventBusTest.php"
do
  IFS='|' read -r NAME PATH TEST <<< "$F"
  S=$([ -e "$PATH" ] && echo "✅" || echo "⚪")
  T=$([ -e "$TEST" ] && echo "✅" || echo "⚠️")
  echo "| $NAME | $S | $T | TBD |" >> PROJECT_STATE.md
done

echo -e "\n## 🔄 آخرین تغییرات" >> PROJECT_STATE.md
git log -5 --pretty="- %h %s (%ad)" --date=short >> PROJECT_STATE.md || true

php scripts/generate_features_md.php || true
php scripts/ai_context_sync.php || true

echo -e "\n## 📌 Features Snapshot" >> PROJECT_STATE.md
if [ -f "FEATURES.md" ]; then
  head -n 15 FEATURES.md >> PROJECT_STATE.md
else
  echo "FEATURES.md not available" >> PROJECT_STATE.md
fi

echo -e "\n---\n*Generated by CI*" >> PROJECT_STATE.md
