name: Advisory
on:
  pull_request:
permissions:
  contents: read
jobs:
  rehearsal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, mbstring, xml, json
          coverage: none
      - name: Install Composer deps
        run: composer install --no-interaction --prefer-dist || true
      - name: QA rehearsal
        run: composer qa:advisory || true
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: advisory-artifacts
          path: artifacts/**
          if-no-files-found: ignore
