name: Apply Scaffold

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Temp folder to scaffold into'
        required: true
        default: 'smartalloc-clean'
      author_name:
        description: 'Composer author/namespace'
        required: true
        default: 'yourname'

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Sanity checks
        shell: bash
        run: |
          set -euxo pipefail
          test -f scaffold-smartalloc-clean.sh
          bash -n scaffold-smartalloc-clean.sh
          head -n 10 scaffold-smartalloc-clean.sh

      - name: Run scaffold script into temp folder
        shell: bash
        run: |
          set -euxo pipefail
          bash scaffold-smartalloc-clean.sh "${{ inputs.project_name }}" "${{ inputs.author_name }}"

      - name: Copy scaffold into repo root (exclude .git)
        shell: bash
        run: |
          set -euxo pipefail
          sudo apt-get update -y
          sudo apt-get install -y rsync
          shopt -s dotglob
          rsync -a \
            --exclude='.git' \
            --exclude='vendor/' \
            "${{ inputs.project_name }}/" ./
          rm -rf "${{ inputs.project_name }}"
          sed -i 's/\r$//' scripts/run-integration.sh || true
          chmod +x scripts/run-integration.sh || true
          ls -la

      - name: Setup PHP & Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer:v2

      - name: Install deps & run unit tests
        shell: bash
        run: |
          set -euxo pipefail
          composer install --no-interaction --prefer-dist
          composer cs || true
          composer test:unit

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: feat/scaffold-apply
          title: 'Scaffold: clean test baseline (unit WP-free, DinD integration, CI)'
          commit-message: 'chore(scaffold): apply clean test baseline'
          labels: scaffold, ci, tests
          body: |
            This PR applies the clean SmartAlloc scaffold:
            - Strict unit isolation (UTC + WordPress contamination sentinel)
            - Minimal Docker-based integration runner (graceful skip locally)
            - GitHub Actions: unit matrix (no Xdebug), DinD integration, composer audit
            - PSR-12 code style commands
            **AC**
            - `composer test:unit` green without touching WP/DB
            - Runner owns `compose up --wait / down -v`, integration skips if Docker absent
            - CI runs 3 jobs (unit, integration, security)
