name: Auto PR Creation
on:
  repository_dispatch:
    types: [codex-pass]
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ci/mysql-setup-${{ github.event.client_payload.run_id || github.run_id }}
          title: "🚀 CI: MySQL Service + WordPress Tests Setup"
          body: |
            ## Automated CI Setup
            
            This PR adds GitHub Actions CI with MySQL 8 service for WordPress testing.
            
            ### Changes
            - ✅ GitHub Actions workflow with MySQL service
            - ✅ Automated test environment setup
            - ✅ Quality gates (Security, Performance, Testing, WP Standards)
            - ✅ Patch-Guard compliance
            - ✅ Site Health monitoring
            
            ### Auto-merge
            This PR will be automatically merged if labeled with `auto_merge`.
            
            Run ID: ${{ github.event.client_payload.run_id || github.run_id }}
          commit-message: "ci: add MySQL service and WordPress test automation"
          labels: |
            ci/cd
            automated
            auto_merge

      - name: Enable auto-merge
        if: steps.cpr.outputs.pull-request-number
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ steps.cpr.outputs.pull-request-number }} \
            --auto \
            --squash \
            --delete-branch
