name: E2E (optional)
on: [workflow_dispatch, push, pull_request]
jobs:
  e2e:
    if: ${{ env.PLAYWRIGHT_E2E == '1' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run E2E tests (Playground)
        run: npm run e2e:all
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
      - name: Upload artifacts (traces, videos)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: |
            test-results
            e2e/downloads
