name: GA Enforce
on:
  workflow_dispatch:
jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, mbstring, xml, json
          coverage: none
      - run: composer install --no-interaction --prefer-dist || true
      - name: Enforce GA thresholds
        run: php scripts/ga-enforcer.php --profile=ga --enforce --junit
      - name: Build dist
        if: success()
        run: |
          php scripts/dist-build.php
          php scripts/dist-manifest.php
          bash scripts/sign-manifest.sh
          mkdir -p artifacts/dist
          (cd dist && zip -qr ../artifacts/dist/dist.zip .)
      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ga-enforce
          path: |
            artifacts/dist/dist.zip
            artifacts/dist/manifest.json
            artifacts/dist/manifest.sha256
            artifacts/dist/manifest.sig
            artifacts/ga/**
          if-no-files-found: ignore
