name: ga-enforce
on:
  pull_request:
  workflow_dispatch:
jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Evaluate 5D Gate
        run: bash scripts/evaluate_scores.sh || exit 1
      - name: Fail on .ci_failure
        run: |
          if [ -f .ci_failure ]; then
            echo "::error file=ai_outputs/last_state.yml::5D gate failed"
            cat .ci_failure
            exit 1
          fi
