name: Manual PR Fallback
on:
  workflow_dispatch:
    inputs:
      pr_branch:
        description: 'Branch to create PR from'
        required: true
      base:
        description: 'Base branch'
        required: true
        default: 'develop'
      pr_title:
        description: 'Title of the PR'
        required: true
      pr_body:
        description: 'Body of the PR'
        required: true
      auto_merge:
        description: 'Enable auto merge'
        default: true
        type: boolean
jobs:
  manual-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ inputs.pr_branch }}
          base: ${{ inputs.base }}
          title: ${{ inputs.pr_title }}
          body: ${{ inputs.pr_body }}
          labels: ${{ inputs.auto_merge && 'auto_merge' || '' }}
      - name: Enable auto-merge
        if: ${{ inputs.auto_merge }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ steps.cpr.outputs.pull-request-number }} \
            --auto \
            --squash \
            --delete-branch
