name: Memory Sync

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}
      - name: Update state
        run: make state
      - name: Run sync
        run: bash scripts/sync_memory_files.sh
      - name: Commit & Push (if changed)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add FEATURES.md PROJECT_STATE.md ai_context.json
          branch="${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}"
          current_branch="$(git rev-parse --abbrev-ref HEAD)"
          if [ "$current_branch" != "$branch" ]; then
            echo "Aborting: checked out $current_branch but expected $branch"
            exit 1
          fi
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: auto-update memory sync files"
            git push origin "HEAD:$branch"
          fi
