name: Memory Sync

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run sync
        run: bash scripts/sync_memory_files.sh
      - name: Commit & Push (if changed)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add FEATURES.md PROJECT_STATE.md ai_context.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: auto-update memory sync files"
            git push
          fi
