name: QA Advisory
on:
  pull_request:
permissions:
  contents: read
jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, mbstring, xml, json
          coverage: none

      - name: Install Composer deps (no dev if project uses lock)
        run: composer install --no-interaction --prefer-dist || true

      - name: QA rehearsal
        run: composer qa:advisory || true

      - name: QA index
        run: php scripts/qa-index.php || true

      - name: Upload QA artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qa-advisory-artifacts
          path: artifacts/**
          if-no-files-found: ignore
