name: Tests

on:
  push:
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Run unit tests
        run: composer test:unit

  integration:
    name: Integration (DinD)
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:27-dind
        privileged: true
        env: { DOCKER_TLS_CERTDIR: "" }
        options: >-
          --health-cmd "docker info >/dev/null 2>&1 || exit 1"
          --health-interval 2s --health-retries 60 --health-timeout 2s
        ports: [ "2375:2375" ]
    env:
      DOCKER_HOST: tcp://localhost:2375
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with: { php-version: '8.2', coverage: none }
      - name: Install Docker CLI & Compose plugin
        run: |
          sudo apt-get update -y
          sudo apt-get install -y docker-ce-cli docker-compose-plugin
          docker version
          docker compose version
      - name: Install deps
        run: composer install --no-interaction --prefer-dist
      - name: Wait for DinD
        run: |
          for i in {1..90}; do docker info >/dev/null 2>&1 && exit 0; sleep 2; done
          echo "Docker daemon not ready"; exit 1
      - name: Run integration via runner
        env: { WP_INTEGRATION: "1" }
        run: |
          chmod +x scripts/run-integration.sh || true
          bash scripts/run-integration.sh
      - name: Archive logs (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-logs
          path: |
            build/reports/**
            coverage/**
            **/*.log
